blogger/config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles do
    resources :comments
  end
  resources :tags
end

blogger/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blogger/app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  validates :title, :body, presence: true
  validates :title, length: { minimum: 8 }

  def tag_list
    tags.join ", "
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|tag| tag.strip.downcase}.uniq
    added_tags = tag_names.collect {|tag| Tag.find_or_create_by(name: tag)}
    self.tags = added_tags
  end
end

blogger/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :body, length: { minimum: 10}
end

blogger/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

blogger/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash.notice = "#{@article.title} was published."
      redirect_to article_path(@article)
    else
      flash.notice = "#{@article.title} couldn't be saved."
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.save
      flash.notice = "You updated '#{@article.title}'."
      redirect_to @article
    else
      flash.notice = "There was a problem updating '#{@article.title}'."
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash.notice = "#{@article.title} was deleted."
      redirect_to articles_path
    else
      flash.notice = "#{@article.title} stayed in the db."
    end
  end

  protected
    def article_params
      params.require(:article).permit(:title, :body, :tag_list)
    end
end

blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index

  end

  def show

  end

  def new

  end

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    if @comment.save
      flash.notice = "Your comment was posted!"
      redirect_to article_path(@comment.article)
    else
      flash.notice = "Couldn't create comment."
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  protected
  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def create

  end
end

blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

blogger/app/helpers/articles_helper.rb
module ArticlesHelper
end

blogger/app/helpers/comments_helper.rb
module CommentsHelper
end

blogger/app/helpers/tags_helper.rb
module TagsHelper
end

blogger/app/views/articles/_comment.html.erb
<div class="comment">
  <h4 class="comment_author">Comment by <%= comment.author %></h4>
  <p class="comment"><%= comment.body %></p>
  <small class="comment-timestamp">posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</small>
</div>

blogger/app/views/articles/_form.html.erb
<%= form_for @article do |a| %>
  <% if @article.errors.any? %>
  <ul class="list-group">
    <% @uncanny.errors.full_messages.each do |e| %>
      <li><%= e %></li>
    <% end %>
  </ul>
  <% end %>

  <div class="form-group">
    <%= a.label(:title) %></br>
    <%= a.text_field(:title, class: 'form-control') %>
  </div>

  <div class="form-group">
    <%= a.label(:body) %></br>
    <%= a.text_area(:body, class: 'form-control') %>
  </div>

  <div class="form-group">
    <%= a.label(:tag_list) %></br>
    <%= a.text_field(:tag_list, class: 'form-control') %>
  </div>

  <div id="submit-button">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
<% end %>

blogger/app/views/articles/edit.html.erb
<h1 class="title">Change Your Mind</h1>
<%= render 'form' %>

blogger/app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles" class="list-group">
  <% @articles.each do |article| %>
    <li class="list-group-item">
      <%= link_to article.title, article_path(article), class: 'article_title' %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path, class: 'new_article' %>

blogger/app/views/articles/new.html.erb
<h1 class="title">New Article</h1>
<%= render 'form' %>

blogger/app/views/articles/show.html.erb
<h1 class="title"><%= @article.title %></h1></br>
<small class="timestamp">Posted <%= @article.created_at %></small>
<p><%= @article.body %></p>
<p id="tags">
  Tags:
  <% @article.tags.each { |tag| %>
     <%= link_to tag.name, tag_path(tag) %>
  <% } %>
</p>
<h3 class="comments-title"><%= puts @article.comments.length %>Comments</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>
<%= link_to "Edit Article", edit_article_path(@article) %>
<%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Truly?"} %>

blogger/app/views/comments/_form.html.erb
<h3 class="title">Post a Comment</h3>
<%= form_for [ @article, @comment ] do |c| %>
<div class="form-group">
  <%= c.label :author, "Your Name" %></br>
  <%= c.text_field :author, class: 'form-control' %>
</div>

<div class="form-group">
  <%= c.label :body, "Your Comment" %></br>
  <%= c.text_area :body, class: 'form-control' %>
</div>

<button type="submit" class="btn btn-primary">Submit</button>

<% end %>

blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-dark" style="background-color: #449966;">
    <a class="navbar-brand" href="#">xAmpl</a>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", articles_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Huh</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Huh</a>
      </li>
  </nav>
  <div id="main-box" class="container">
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </div>
  </body>
</html>

blogger/app/views/tags/index.html.erb
<h1 class="title">All Tags</h1>
<ul id="tags" class="list-group">
  <% @tags.each do |tag| %>
    <li class="list-group-item">
      <%= link_to tag.name, tag_path(tag), class: 'tag_title' %>
    </li>
  <% end %>
</ul>

blogger/app/views/tags/show.html.erb
<h1 id="title">Articles tagged <%= @tag.name %></h1>
<ul id="articles" class="list-group">
  <% @tag.articles.each do |article| %>
    <li class="list-group-item">
      <%= link_to article.title, article_path(article), class: 'article_title' %>
    </li>
  <% end %>
</ul>